language: python
python:
- "3.7-dev"
install:
- pip install -r requirements.txt
env:
- DJ_DEBUG=False DATABASE_URL=postgres://postgres@localhost/travisdb
before_script:
- psql -c "CREATE SCHEMA IF NOT EXISTS travisdb;" -U postgres
- python manage.py migrate --noinput
script:
- python manage.py test