# Generated by Django 2.0.3 on 2018-11-22 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Year', models.CharField(max_length=100)),
                ('Rated', models.CharField(max_length=100)),
                ('Released', models.CharField(max_length=100)),
                ('Runtime', models.CharField(max_length=100)),
                ('Genre', models.CharField(max_length=100)),
                ('Director', models.CharField(max_length=100)),
                ('Writer', models.CharField(max_length=1000)),
                ('Actors', models.CharField(max_length=1000)),
                ('Plot', models.CharField(max_length=1000)),
                ('Language', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Awards', models.CharField(max_length=100)),
                ('Poster', models.CharField(max_length=1000)),
                ('Metascore', models.CharField(max_length=100)),
                ('imdbRating', models.CharField(max_length=100)),
                ('imdbVotes', models.CharField(max_length=100)),
                ('imdbID', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('DVD', models.CharField(max_length=100)),
                ('BoxOffice', models.CharField(max_length=100)),
                ('Production', models.CharField(max_length=100)),
                ('Website', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(max_length=100)),
                ('Value', models.CharField(max_length=100)),
                ('Movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ratings', to='movie_api.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='movie_api.Movie'),
        ),
    ]
